stages:
- name: front build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: cd "front"
  - runScriptConfig:
      image: node:latest
      shellScript: ls
- name: npm build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: pwd
timeout: 60
