stages:
- name: front install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: node -v
- name: front build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm -v
timeout: 60
