stages:
- name: npm install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install front
- name: npm build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: cd front
- name: dd
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ls
timeout: 60
