stages:
- name: front install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: pwd
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  - runScriptConfig:
      image: node:latest
      shellScript: cd front/
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  - runScriptConfig:
      image: node:latest
      shellScript: node -v
  - runScriptConfig:
      image: node:latest
      shellScript: npm -v
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
timeout: 60
