stages:
- name: front install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: cd front/
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
- name: front build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm -v
timeout: 60
